packaging_format = 2

id = "rocketchat"
name = "Rocket.Chat"
description.en = "Team collaboration communication platform"
description.fr = "Plateforme de communication collaborative en équipe"

version = "6.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://rocket.chat/"
demo = "https://cloud.rocket.chat/trial"
admindoc = "https://docs.rocket.chat/"
userdoc = "https://docs.rocket.chat/guides/user-guides"
code = "https://github.com/RocketChat/Rocket.Chat"

[integration]
yunohost = ">= 11.1.14"
architectures = ["amd64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/rocketchat"

    [install.init_main_permission]
    help.en = "You must activate 'Visitors' if you want to connect a Mobile or desktop client to Rocket.Chat. This can be changed later via the webadmin."
    help.fr = "Vous devez activer 'Visiteurs' si vous souhaitez connecter un client mobile ou desktop à Rocket.Chat. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
    [resources.sources]

        [resources.sources.app]
        url = "https://releases.rocket.chat/6.0.0/download"
        sha256 = "c2c60f66f345626c04af6c172202ff3e423884e2ca54d2d9553506bec816b1e0"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "apt-transport-https build-essential gzip curl fontconfig graphicsmagick"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"
