test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.ca35dcf1205733c8cf94cb2dc32a9c899ae93d1d.name = "Upgrade from 6.3.1~ynh1"
    